- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb client
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: get the catagories count
  ansible.builtin.command: mongo --host mongodb.pradeepshop.online --quiet --eval 'db = db.getSiblingDB("{{component}}"); db.products.count()'
  register: product_count

- name: "load {{component}} data"
  ansible.builtin.command: "mongo --host mongodb.pradeepshop.online < /app/schema/{{component}}.js"
  when: product_count.stdout == "0"
